# Generated by Django 5.0.7 on 2024-07-25 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('image', models.ImageField(default='/default.png', upload_to='category/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام محصول')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت')),
                ('image', models.ImageField(default='/default.png', upload_to='product/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='منتشر شده در ')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
