# Generated by Django 5.0.7 on 2024-08-04 10:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='عیار'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='جنس'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='منتشر شده در '),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/default.png', upload_to='product/', verbose_name='تصویر اصلی'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/', verbose_name='تصویر')),
                ('uploaded_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='بارگذاری شده در ')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='product/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='ویدیو')),
                ('uploaded_at', django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now, verbose_name='بارگذاری شده در ')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='products.product')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها',
            },
        ),
    ]
